// Package firewall renders the nftables ruleset that enforces each device's
// access rules, and applies it.
//
// Rendering is a pure function of Config, so the exact ruleset can be
// reviewed and golden-tested. Tunnelward owns one table and replaces it
// atomically on every change; it never touches any other table.
package firewall

import (
	"cmp"
	"errors"
	"fmt"
	"net/netip"
	"regexp"
	"slices"
	"strings"
	"unicode"

	"github.com/ap-andersson/tunnelward/internal/model"
)

// Table is the name of the nftables table (family inet) owned by Tunnelward.
const Table = "tunnelward"

// NonPublic lists the IPv4 ranges that the model.Internet alias excludes.
// The tunnel network is added to this set when rendering.
var NonPublic = []netip.Prefix{
	netip.MustParsePrefix("0.0.0.0/8"),      // "this network"
	netip.MustParsePrefix("10.0.0.0/8"),     // private
	netip.MustParsePrefix("100.64.0.0/10"),  // carrier-grade NAT
	netip.MustParsePrefix("127.0.0.0/8"),    // loopback
	netip.MustParsePrefix("169.254.0.0/16"), // link local
	netip.MustParsePrefix("172.16.0.0/12"),  // private
	netip.MustParsePrefix("192.0.0.0/24"),   // IETF protocol assignments
	netip.MustParsePrefix("192.168.0.0/16"), // private
	netip.MustParsePrefix("198.18.0.0/15"),  // benchmarking
	netip.MustParsePrefix("224.0.0.0/4"),    // multicast
	netip.MustParsePrefix("240.0.0.0/4"),    // reserved, incl. broadcast
}

// Peer is one enabled device and its effective rules.
type Peer struct {
	ID    int64
	Name  string
	IP    netip.Addr
	Rules []model.SourcedRule
}

// Config is everything the ruleset depends on.
type Config struct {
	Interface  string // WireGuard interface, e.g. "wg0"
	TunnelCIDR netip.Prefix
	Peers      []Peer // enabled devices only
}

var interfaceName = regexp.MustCompile(`^[A-Za-z0-9_.-]{1,15}$`)

// Render returns the nftables ruleset for cfg, to be fed to `nft -f`.
//
// Policy, for traffic arriving on the WireGuard interface (replies to
// allowed connections always pass):
//   - forward: a device may reach a destination only if one of its rules
//     allows it. This includes other devices (peer-to-peer).
//   - input (the server itself): same, except that model.Internet rules do
//     not apply, so the server is only reachable through explicit rules.
//   - IPv6 is always dropped.
//
// New connections from outside the tunnel to devices are dropped. Traffic
// from devices to anywhere outside the tunnel is masqueraded.
func Render(cfg Config) (string, error) {
	if !interfaceName.MatchString(cfg.Interface) {
		return "", fmt.Errorf("invalid interface name %q", cfg.Interface)
	}
	settings := model.Settings{TunnelCIDR: cfg.TunnelCIDR}
	if !cfg.TunnelCIDR.IsValid() || !cfg.TunnelCIDR.Addr().Is4() || cfg.TunnelCIDR != cfg.TunnelCIDR.Masked() {
		return "", fmt.Errorf("invalid tunnel network %s", cfg.TunnelCIDR)
	}

	peers := slices.Clone(cfg.Peers)
	slices.SortFunc(peers, func(a, b Peer) int { return a.IP.Compare(b.IP) })
	seenIP := map[netip.Addr]bool{}
	seenID := map[int64]bool{}
	merged := make([][]mergedRule, len(peers))
	for i, p := range peers {
		if p.ID <= 0 || seenID[p.ID] {
			return "", fmt.Errorf("device %q: invalid or duplicate ID %d", p.Name, p.ID)
		}
		if err := settings.CheckDeviceIP(p.IP); err != nil {
			return "", fmt.Errorf("device %q: %w", p.Name, err)
		}
		if seenIP[p.IP] {
			return "", fmt.Errorf("device %q: IP %s is used by another device", p.Name, p.IP)
		}
		seenID[p.ID], seenIP[p.IP] = true, true

		rules, err := mergeRules(p.Rules)
		if err != nil {
			return "", fmt.Errorf("device %q: %w", p.Name, err)
		}
		merged[i] = rules
	}

	iface := quote(cfg.Interface)
	w := &writer{}
	w.line("#!/usr/sbin/nft -f")
	w.line("# Generated by Tunnelward. Do not edit, changes will be overwritten.")
	w.line("")
	w.line("# Create the table if missing, then delete it, so the definition below")
	w.line("# replaces it completely. nft applies the whole file in one transaction.")
	w.line("table inet %s", Table)
	w.line("delete table inet %s", Table)
	w.line("")
	w.open("table inet %s", Table)

	w.open("set nonpublic")
	w.line("type ipv4_addr")
	w.line("flags interval")
	w.line("elements = { %s }", strings.Join(nonPublicElements(cfg.TunnelCIDR), ", "))
	w.close()

	w.line("")
	w.open("chain forward")
	w.line("type filter hook forward priority filter; policy accept;")
	w.line("iifname != %s oifname != %s return", iface, iface)
	w.line("ct state invalid drop")
	writeReplyAccept(w)
	w.line("# Anything else from outside the tunnel to devices.")
	w.line("iifname != %s drop", iface)
	w.line("meta nfproto ipv6 drop")
	writeDispatch(w, peers, "fwd")
	w.line("drop")
	w.close()

	w.line("")
	w.open("chain input")
	w.line("type filter hook input priority filter; policy accept;")
	w.line("iifname != %s return", iface)
	w.line("ct state invalid drop")
	writeReplyAccept(w)
	w.line("meta nfproto ipv6 drop")
	writeDispatch(w, peers, "in")
	w.line("drop")
	w.close()

	w.line("")
	w.open("chain postrouting")
	w.line("type nat hook postrouting priority srcnat; policy accept;")
	w.line("ip saddr %s oifname != %s masquerade", cfg.TunnelCIDR, iface)
	w.close()

	for i, p := range peers {
		for _, kind := range []string{"fwd", "in"} {
			w.line("")
			w.line("# Device %d %s (%s), %s", p.ID, comment(fmt.Sprintf("%q", p.Name)), p.IP, kindDescription[kind])
			w.open("chain %s", chainName(kind, p.ID))
			n := 0
			for _, r := range merged[i] {
				if kind == "in" && r.Destination == model.Internet {
					continue
				}
				w.line("# %s", comment(r.origin))
				w.line("%s", ruleExpr(r.Rule))
				n++
			}
			if n == 0 {
				w.line("# No rules: everything is dropped.")
			}
			w.close()
		}
	}

	w.close()
	return w.String(), nil
}

var kindDescription = map[string]string{
	"fwd": "traffic through the server",
	"in":  "traffic to the server itself",
}

func chainName(kind string, id int64) string {
	return fmt.Sprintf("%s_dev_%d", kind, id)
}

// writeReplyAccept lets replies through without checking rules. Only the
// reply direction is accepted this way: every packet a device sends (the
// original direction) goes through its rules, including packets of
// connections that are already open, so removing a rule takes effect
// immediately instead of when the connection ends.
func writeReplyAccept(w *writer) {
	w.line("# Replies skip the rules. Everything a device sends is checked, also on open connections.")
	w.line("ct state established,related ct direction reply accept")
}

// writeDispatch jumps to the per-device chain matching the source address.
// Packets from unknown sources fall through to the caller's drop.
func writeDispatch(w *writer, peers []Peer, kind string) {
	if len(peers) == 0 {
		return
	}
	w.open("ip saddr vmap")
	for i, p := range peers {
		sep := ","
		if i == len(peers)-1 {
			sep = ""
		}
		w.line("%s : jump %s%s", p.IP, chainName(kind, p.ID), sep)
	}
	w.close()
}

func nonPublicElements(tunnel netip.Prefix) []string {
	prefixes := slices.Clone(NonPublic)
	covered := slices.ContainsFunc(prefixes, func(p netip.Prefix) bool {
		return p.Bits() <= tunnel.Bits() && p.Contains(tunnel.Addr())
	})
	if !covered {
		prefixes = append(prefixes, tunnel)
		slices.SortFunc(prefixes, comparePrefix)
	}
	out := make([]string, len(prefixes))
	for i, p := range prefixes {
		out[i] = p.String()
	}
	return out
}

// mergedRule is a rule after de-duplication, with all its origins.
type mergedRule struct {
	model.Rule
	origin string
}

// mergeRules normalizes rules and merges duplicates (same destination,
// protocol and ports), keeping a sorted, deterministic order.
func mergeRules(rules []model.SourcedRule) ([]mergedRule, error) {
	type key struct {
		dest     string
		proto    model.Protocol
		from, to int
	}
	byKey := map[key]*mergedRule{}
	var out []*mergedRule
	for _, sr := range rules {
		r := sr.Rule
		if err := r.Normalize(); err != nil {
			return nil, fmt.Errorf("rule from %s: %w", sr.Source, err)
		}
		origin := sr.Source
		if r.Comment != "" {
			origin += ": " + r.Comment
		}
		k := key{r.Destination, r.Protocol, r.PortFrom, r.PortTo}
		if m, ok := byKey[k]; ok {
			m.origin += "; " + origin
			continue
		}
		r.Comment = ""
		m := &mergedRule{Rule: r, origin: origin}
		byKey[k] = m
		out = append(out, m)
	}
	slices.SortFunc(out, func(a, b *mergedRule) int {
		return cmp.Or(
			compareDestination(a.Rule, b.Rule),
			cmp.Compare(a.Protocol, b.Protocol),
			cmp.Compare(a.PortFrom, b.PortFrom),
			cmp.Compare(a.PortTo, b.PortTo),
		)
	})
	result := make([]mergedRule, len(out))
	for i, m := range out {
		result[i] = *m
	}
	return result, nil
}

// compareDestination orders the internet alias first, then prefixes.
func compareDestination(a, b model.Rule) int {
	pa, okA := a.DestinationPrefix()
	pb, okB := b.DestinationPrefix()
	switch {
	case !okA && !okB:
		return 0
	case !okA:
		return -1
	case !okB:
		return 1
	}
	return comparePrefix(pa, pb)
}

func comparePrefix(a, b netip.Prefix) int {
	return cmp.Or(a.Addr().Compare(b.Addr()), cmp.Compare(a.Bits(), b.Bits()))
}

// ruleExpr renders a normalized rule as one nft rule ending in accept.
// Every value comes from a validated, typed field, never raw user text.
func ruleExpr(r model.Rule) string {
	var parts []string
	if p, ok := r.DestinationPrefix(); !ok {
		parts = append(parts, "ip daddr != @nonpublic")
	} else if p.IsSingleIP() {
		parts = append(parts, "ip daddr "+p.Addr().String())
	} else if p.Bits() > 0 {
		parts = append(parts, "ip daddr "+p.String())
	}

	ports := ""
	if r.PortFrom != 0 {
		ports = fmt.Sprint(r.PortFrom)
		if r.PortTo != r.PortFrom {
			ports = fmt.Sprintf("%d-%d", r.PortFrom, r.PortTo)
		}
	}
	switch r.Protocol {
	case model.ProtoICMP:
		parts = append(parts, "meta l4proto icmp")
	case model.ProtoTCP, model.ProtoUDP:
		if ports != "" {
			parts = append(parts, fmt.Sprintf("%s dport %s", r.Protocol, ports))
		} else {
			parts = append(parts, "meta l4proto "+string(r.Protocol))
		}
	case model.ProtoTCPUDP:
		parts = append(parts, "meta l4proto { tcp, udp }")
		if ports != "" {
			parts = append(parts, "th dport "+ports)
		}
	}
	return strings.Join(append(parts, "accept"), " ")
}

// quote returns s as an nft string literal. Only used for values that have
// already been validated to contain no quotes or special characters.
func quote(s string) string {
	return `"` + s + `"`
}

// comment makes user-provided text safe for a '#' comment line by replacing
// anything non-printable (including newlines) with '?'.
func comment(s string) string {
	return strings.Map(func(r rune) rune {
		if unicode.IsPrint(r) {
			return r
		}
		return '?'
	}, s)
}

// writer builds indented nft text.
type writer struct {
	b     strings.Builder
	depth int
}

func (w *writer) line(format string, args ...any) {
	s := fmt.Sprintf(format, args...)
	if s != "" {
		w.b.WriteString(strings.Repeat("\t", w.depth))
		w.b.WriteString(s)
	}
	w.b.WriteByte('\n')
}

func (w *writer) open(format string, args ...any) {
	w.line(format+" {", args...)
	w.depth++
}

func (w *writer) close() {
	if w.depth == 0 {
		panic(errors.New("firewall: unbalanced close"))
	}
	w.depth--
	w.line("}")
}

func (w *writer) String() string { return w.b.String() }
